s = open('24 пример файла').readline()

s = s.replace("**", "x")
s = s.replace("--", "x")
s = s.replace("*x", "x")
s = s.replace("x*", "x")
s = s.replace("-x", "x")
s = s.replace("x-", "x")
s = s.replace("-*", "x")
s = s.replace("*-", "x")
s = s.replace("0-", "x")
s = s.replace('0*', 'x')
s = s.replace("-0", "x")
s = s.replace('*0', 'x')

s = s.replace("**", "x")
s = s.replace("--", "x")
s = s.replace("*x", "x")
s = s.replace("x*", "x")
s = s.replace("-x", "x")
s = s.replace("x-", "x")
s = s.replace("-*", "x")
s = s.replace("*-", "x")
s = s.replace("0-", "x")
s = s.replace('0*', 'x')
s = s.replace("-0", "x")
s = s.replace('*0', 'x')


print(s)
s=s.split("x")
print(s)

print(len(max(s, key=len)), max(s, key=len))