f = open('24 (1).txt')
s = f.readline()
s = s.replace('A', "b")
s = s.replace('B', 'b')
s = s.replace('C', 'b')
s = s.replace('6', "0")
s = s.replace('7', '0')
s = s.replace('8', '0')
s = s.replace('9', '0')
s = s.replace('bb', 'b b')
s = s.replace('00', '0 0')
s = s.replace('bb', 'b b')
s = s.replace('00', '0 0')
s = s.split()
print(len(max(s, key=len)))

